language: java
php:
  - nightly

install:
  - rm -rf `pwd`/vendor
  - composer require "phpdocumentor/phpdocumentor:2.8.5"
  - sudo apt-get install graphviz
#  - sudo chmod 755 .travis.phpdoc.sh
#  - export PATH="`pwd`/vendor/bin:$PATH"
#  - phpdoc -d src/main/generated -t target/phpdoc --template="responsive-twig"
#  - php bin/phpdoc
#  - vendor/bin/phpdoc

script: phpdoc -d src/main/generated -t target/phpdoc --template="responsive-twig"
