language: java
php:
  - nightly

#install:
#  - rm -rf `pwd`/vendor
#  - composer require "phpdocumentor/phpdocumentor:v3.0.0-alpha.4"
#  - sudo apt-get install graphviz
#  - sudo chmod 755 .travis.phpdoc.sh
#  - export PATH="`pwd`/vendor/bin:$PATH"
#  - phpdoc -d src/main/generated -t target/phpdoc --template="responsive-twig"
#  - php bin/phpdoc
#  - vendor/bin/phpdoc

script: php phpdoc.phar -q -d src/main/generated -t target/phpdoc --template="responsive-twig"
