language: java
php:
  - nightly

install:
  - composer require "phpdocumentor/phpdocumentor:2.8.5"
  - sudo apt-get install graphviz
  - sudo chmod 755 .travis.phpdoc.sh
  - ll
  - php vendor/bin/phpdoc

jobs:
  include:
  - stage: test
    name: "Oracle"
    jdk: oraclejdk8
    script: mvn -q clean verify -B