language: java
php:
  - nightly

install:
  - composer require "phpdocumentor/phpdocumentor:2.8.5"
  - sudo apt-get install graphviz
  - sudo chmod 755 .travis.phpdoc.sh
  - export PATH="`pwd`/vendor/bin:$PATH"
#  - phpdoc -d src/main/generated -t target/phpdoc --template="responsive-twig"
#  - php bin/phpdoc
#  - vendor/bin/phpdoc

jobs:
  include:
  - stage: test
    name: "openjdk8"
    jdk: openjdk8
    script: mvn -q clean verify -B